AllCops:
  NewCops: enable
  TargetRubyVersion: 3.1.1
  SuggestExtensions: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/EndOfLine:
  Enabled: false

GemSpec/RequireMFA:
  Enabled: false

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 140
